### ISSUE TITLE
Signatures are not validated and can cause #request_token to raise errors

### ISSUE THREAD

**Issue by csaunders** [Shopify/shopify_api#163]
See #125 for implementation examples

**Comment by N19270** [comment]
I got same error when following step 4 in the guide:
> `token = session.request_token(params)`.

Is there a workaround to this issue? We'd love to be able to use this rather than rest-client.

Though we've found that if we fetch the token by accessing the API directly using rest-client, it kinda works. By kinda, 'products' API works but the other APIs return 403.

**Comment by csaunders** [comment]
Did you require more scopes than just products? The default example just shows `read_orders`.

If you are using our omniauth gem, make sure you update your configuration to include the [additional permissions you require](http://docs.shopify.com/api/authentication/oauth#scopes)
