### ISSUE TITLE
Pass UPC in Order Line Item Data

### ISSUE THREAD

**Issue by reidblomquist** [Shopify/shopify_api#219]
Would be nice to include UPC in order data responses as many fulfillment systems will require an additional lookup of said data.

**Comment by ShayneP** [comment]
At this point, it's unlikely that we'll start serializing more default data in the REST Order response.

The good news is that with GraphQL, you can request any data that you want in your original request, and the response will include the value.

Information about how to use GraphQL with the gem can be found in [this section](https://github.com/Shopify/shopify_api#6a-making-requests-to-the-graphql-api) of the improved readme.

**Comment by clement911** [comment]
> At this point, it's unlikely that we'll start serializing more default data in the REST Order response.

Is the REST API being treated as a second citizen now with no more new fields added?
Yes, the GraphQL API can help but the problem is that it also means webhooks will not get new fields, since the payloads are based on the REST payloads.

**Comment by ShayneP** [comment]
It's not that we aren't adding new fields to REST, it's that the UPC has never been serialized as a part of an order, and we're unlikely to revisit that decision. The order object is already quite large, and most clients don't need the UPC. For clients that do, the GraphQL API is a great solution.

GraphQL subscriptions are coming at some point fairly soon, so that will solve the Webhook issue you're mentioning :)
