### ISSUE TITLE
ShopifyQL

### ISSUE THREAD

**Issue by corehook** [Shopify/shopify_api#258]
Hello! How i can send send query to AnalyticsAPI ? I want get all page views through ShopifyQL. 
I has signed by oauth shop owner :
```ruby
[10] pry(main)> session = project.shopify_session
=> #<ShopifyAPI::Session:0x007fbc5af0bea0 @token="229170ac1308313afd41**d21bd1a8a3", @url="supersecret-3.myshopify.com">
```

**Comment by tylermercier** [comment]
@corehook check the [docs](https://docs.shopify.com/api/tutorials/analytics-api) on how to get started.  Just note that the Analytics API is only supported from within embedded apps at this time.

**Comment by mrpunkin** [comment]
Is there a reason for this @tylermercier? I know lots of people are looking for server-side support for ShopifyQL / Analytics and Shopify seems to not have anything to offer regarding that yet.

**Comment by tylermercier** [comment]
What type of app are you trying to build Bryan? Curious how the Analytics API could be useful to you.

**Comment by mrpunkin** [comment]
We are a book publisher who works with vendors (Newspapers) to publish coffee table history books. Our clients are not staff members, but need to stay up to date on gross/net sales figures regarding their titles. We'd love to have a dashboard type app that allows us to present them with up to date sales figures without having to handle every order webhook ourselves and store the data accordingly, and without having to give them access to our store backend.

Giving them exported reports from within Shopify isn't realistic either. We have probably over 500 clients who a good chunk of want to know those figures often, and our staff just doesn't have the time to be exporting tailored reports multiple times a day for them. 

Without the Analytics API being made server-side where we can leverage it behind our own auth system and such we will have to export daily or monthly reports, import them elsewhere, and then run our app against that data. We'd love to just leverage the powerful system Shopify already has available.

The other downside to it being locked into the EASDK is that it doesn't allow for any automated tasks such as cron jobs or background jobs to fetch or use data because it'll only work for a user logged in with client-side code running in their browser.

**Comment by tylermercier** [comment]
If you could schedule a report to be emailed to a specific person, would that do most of what you need?

**Comment by mrpunkin** [comment]
No, these are clients that decide when they want the data, and then go to get it. Scheduling a report would then mean we'd be fielding calls asking for data before the report comes in. 

Also it'd just be super useful for our own accounting reconciliation and stuff to be able to build tailored views off of the data without relying on Shopify reports. Merging it with other sales channels other than Shopify, etc.

**Comment by mrpunkin** [comment]
If anything, having the Analytics data accessible via server-side scripting would be safer than not making it available. The alternative is storing all that data off-Shopify just to build out your custom apps. Making it available on an on-demand basis where only authenticated systems can access it when necessary removes the need for customers / developers to duplicate customer / order data for their own analytics purposes.

**Comment by mrpunkin** [comment]
Continuing to ask for this nearly two years after people started wondering about it. There are many forum threads on the Shopify forums asking for the same thing. Please consider this.

**Comment by ianks** [comment]
Chiming in here. We have a large need for accessing the analytics API server side as well. It is crucial for us to provide insights to some of our clients, and currently, we are unable to do this. Please consider opening up the analytics API for offline access.
