### ISSUE TITLE
abandoned checkouts

### ISSUE THREAD

**Issue by orenmazor** [Shopify/shopify_api#296]
How are abandoned checkouts exposed here? I was expecting it to be something like `ShopifyAPI::AbandonedCheckout`, but it looks like maybe it's just `ShopifyAPI::Checkout`?

**Comment by maartenvg** [comment]
Doesn't look like it has been added. 

I think this would be the code:

```ruby
module ShopifyAPI
  class AbandonedCheckout < Base
    self.element_name = 'checkout'
  end
end
```

**Comment by orenmazor** [comment]
@maartenvg right now I'm grabbing Checkouts and looking for open ones that are over a certain age, but that feels hacky

**Comment by justinstern** [comment]
@orenmazor `ShopifyAPI::Checkout` is indeed the correct resource to use, and even though they are referred to as "abandoned checkouts" if you look at the request URL it's `/admin/checkouts.json`. It's one of the simpler resource APIs, with only a count and get all request.

Shopify considers a checkout as "abandoned" the instant that someone has entered their shipping/billing information, which makes sense from a logic perspective, since there is no way programmatically to determine whether a person has "abandoned" an order (to be sure you'd have to call them up and ask, and even then they might lie, ha ha).

Instead, you make your own determination as to when an order is considered "abandoned" based on your requirements, logic, and experimentation. Considering existing (non-completed) checkouts over a certain age as being "abandoned" is a good solution in general.

**Comment by justinstern** [comment]
@orenmazor oh, I'd be remiss if I didn't add that the [Shopify APIs & Technology forum](https://ecommerce.shopify.com/c/shopify-apis-and-technology) is the best and preferred place to post these sorts of question 😄

**Comment by orenmazor** [comment]
Gotcha thanks. 

Re the forum, I prefer to ask here because depending on the answer, I may need to make a pull request and having the traceability of the issue helps in code reviews and context.

**Comment by orenmazor** [comment]
@maartenvg I can pr that change if you guys want it, but it sounds like it's an opinionated addition to an otherwise unopinionated gem.

**Comment by maartenvg** [comment]
No, I was wrong. The abandoned checkouts endpoint is called `/admin/checkouts` so the existing checkout.rb should already work.

**Comment by orenmazor** [comment]
Cool, no worries! the api doc was just misleading me into thinking these are two separate things. I'm sure it's just @jbruton's fault tbh

**Comment by orenmazor** [comment]
closing because answered

**Comment by iyerushalmi** [comment]
Hello, are there certain parameters that need to be passed on the ShopifyAPI::Checkout.all query in order to return ONLY abandoned checkouts? I am having a hard time separating abandoned checkouts from all the remaining checkouts.
