### ISSUE TITLE
Publication support?

### ISSUE THREAD

**Issue by tispratik** [Shopify/shopify_api#344]
Is there support for publication? By default the new product created is published on online store only. I am trying to see how i can make it so that i can mark the publishing setting for instagram or other channels as well.

**Comment by jamiemtdwyer** [comment]
This action isn't currently supported through the Shopify API.

Since this repository is specifically regarding the functionality of the Ruby client library (`shopify_api`), I'm going to go ahead and close this. If this functionality is added to the Shopify API, I'll re-open this feature request to add support in this library.

For more general discussion about the Shopify API, I recommend visiting our [developer forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology).
