### ISSUE TITLE
Email sending API

### ISSUE THREAD

**Issue by tin-tnguyen** [Shopify/shopify_api#376]
Hi all,

Currently I am developing an embedded app using Shopify API. The app now requires to send mail from shop owner/merchant to customers with provided email address. Normally shop owners can do that by clicking on customer emails displayed within Admin page at Order menu. 

However it was hard for me to find such function in the API. So my question is is it possible to send email with Shopify API? If not, would this feature be available in the future?

Thanks

**Comment by jamiemtdwyer** [comment]
Hey tin,

Shopify does not provide such an API – you'll have to handle transactional e-mails through your own system.

In the future, [general inquiries about the API should be directed here](https://ecommerce.shopify.com/c/shopify-apis-and-technology) rather than this repository. This repository should be reserved for issues specifically regarding the Ruby client library.
