### ISSUE TITLE
Get a checkout by token and modify it?

### ISSUE THREAD

**Issue by jerry-gdd** [Shopify/shopify_api#400]
The shopify admin API has 2 endpoint that let yout find a checkout by token and modify it.

see https://help.shopify.com/api/reference/checkout
GET /admin/checkouts/#{token}.json
PUT /admin/checkouts/#{token}.json

What's the call to make to achieve the same thing with this gem?

I tried ShopifyAPI::Checkout.find({:token, "ff8b7ae7256d1200ca620d235cc27b23"})

But it returns a 403 forbidden. My rails app is linked to a private app with read and write access enabled on everything.

**Comment by AnatolZaitsev** [comment]
From [Admin API documentation for Checkout](https://help.shopify.com/api/reference/checkout):

> The Checkout API is for use only with the Sales Channel SDK. You can't use the Checkout API to create a new checkout for an individual store. To do so, you need to use an SDK that's powered by the Storefront API instead, such as the Javascript Buy, iOS Buy, and Android Buy SDKs.

So, I guess it's necessary [to configure Checkout API](https://help.shopify.com/api/tutorials/sell-through-the-checkout-api) additionally.

**Comment by AnatolZaitsev** [comment]
You can find checkout via token to do:
```
checkouts = ShopifyAPI::Checkout.find(:all)
checkouts.find { |record| record.token == your_token }
```

**Comment by jamiemtdwyer** [comment]
If you want to retrieve a Checkout by `token` rather than `id`, you'll need to override the definition of the `Checkout` class in your project.

```
module ShopifyAPI
  class Checkout < ShopifyAPI::Base
    include RemoteErrors

    def id
      @attributes[:token]
    end

    class Payment < ShopifyAPI::Base
      self.prefix = "/admin/checkouts/:checkout_id/"
    end

    class ShippingRate < ShopifyAPI::Base
      self.prefix = "/admin/checkouts/:checkout_id/"
    end
  end
end
```

The [Abandoned Checkouts API](https://help.shopify.com/api/reference/abandoned_checkouts) and the [Checkout API](https://help.shopify.com/api/reference/checkout) share the same endpoint, hence the need to override the class definition.

That being said, if your goal is to modify a checkout that was created by Online Store, I can't guarantee that's possible.
