### ISSUE TITLE
Updating product when option already exists gives "Options are not unique"

### ISSUE THREAD

**Issue by realadeel** [Shopify/shopify_api#49]
Details in this discussion that was last updated December 2012:
http://stackoverflow.com/questions/12658002/what-is-the-best-way-to-prevent-to-see-options-are-not-unique-error

Chris Saunders says:

> there is a bug in the API when updating products and you are passing in an option that already exists. The error message is actually quite misleading and is being worked on at the moment.

I'm running into this in v3.0.3. Any progress on this or workaround?

Last update by Chris was:

> The issue seemed trivial on the surface but there's a bit of work that needs to be done so we haven't had the chance to properly fix it yet.

**Comment by meisbellajack** [comment]
The options are not unique error happens because Shopify thinks you are trying to create a brand new variant with duplicate options, rather than updating your existing one.

When you send a <variant> block during a product update without specifying that variant's unique ID, Shopify treats it as an instruction to add a new option row. Since your new row has the exact same value (<option1>) as the one already saved in the database, the API blocks it because variant combinations must be entirely unique.

- To fix this, you must include the <id> tag of the specific variant you want to update inside your modify XML payload. 
- By passing the variant ID alongside your updated price or SKU, Shopify will modify the existing data correctly instead of trying to generate a duplicate variant.
 

If you are modifying backend scripts to bypass layout restrictions or build a highly customized ordering workflow, keep in mind that Shopify restricts all products to a strict limit of 3 options and 100 variants natively.

Instead of dealing with strict API structure errors and constantly adjusting your code, you can use our app, Misk Variant & Product Options. It allows you to globally add infinite choices, visual color swatches, text inputs, and file upload fields directly onto your front-end layout code-free bypassing native platform limits completely while keeping your backend data completely clean!
