### ISSUE TITLE
"You can find released versions here" points to incorrect line

### ISSUE THREAD

**Issue by vfonic** [Shopify/shopify_api#570]
In readme. I actually don't know where it should point to. You'd probably want to have it point to an exact line on an exact commit (not on `master` like now). You'd probably also want to extract the version numbers to a constant where it's easier to find it. I still don't know what API version numbers are supported nor when exactly new API version is released (5pm? 5pm in which timezone? On what day?)

**Comment by 0ptimusrhyme** [comment]
Hey @vfonic, [this doc](https://help.shopify.com/en/api/versioning) specifies that stable version releases would occur at 5pm UTC. If you're reading that anywhere that the time zone is not specified let me know and we can get that corrected.

We agree that we should point to the specific commit's known versions specification. We'll fix that. We're going to move the known versions specification into a `versions.rb` file and point to that instead, which should be much easier to reference

If we're pointing directly to the aforementioned file, I'm not sure if it's of much more benefit to store them in a constant since it will already be such a simple file.

Thanks!

**Comment by vfonic** [comment]
Thanks for the quick reply and @tylerball for quick PR fixing this issue! 🎉
