### ISSUE TITLE
API Version 2019-07 pagination

### ISSUE THREAD

**Issue by bgmat** [Shopify/shopify_api#595]
Hi,

The 2019-07 API version changed the pagination for few resources as described [here](https://help.shopify.com/en/api/guides/paginated-rest-results). 

The Product is one of the resources impacted.
I don't see any Breaking change notice, but I think it should be, because the 'page' parameter no longer works and returns an error.

Also, it would be nice to know if you plan to release API support for this feature.

Thank you

**Comment by jiri-hacmac** [comment]
Hi,
this feature has already been implemented and merged into master with #594 
Great work @garethson  👍
Why is the cursor based pagination targeted to the unstable API version?
As already mentioned some endpoints support this pagination already since 2019-07.
It would be great to to get this feature into a release soon.

**Comment by garethson** [comment]
@jiri-hacmac Thanks! I've since updated the readme (see https://github.com/Shopify/shopify_api/pull/599) to denote that relative cursor navigation is now available on _all_ endpoints using the `2019-10` and later API versions.

Since only some of the endpoints were available in Shopify on `2019-07`, we didn't want to add partial support in this library, but now that every endpoint is available, you can simply use `2019-10` (or `unstable`, which is not recommended for production use).

**Comment by garethson** [comment]
Closing this issue, but feel free to drop in any questions regarding this library's support for this type pagination here.
