### ISSUE TITLE
Correct way to handle a 202 Accepted response

### ISSUE THREAD

**Issue by tolgap** [Shopify/shopify_api#618]
I've run into quite a difficult issue with Shopify API. I use DraftOrders in my private app to "model" a checkout object. In this DraftOrder, I set shipping addresses and shipping lines. When saving the DraftOrder, the PUT operation always ends up being 202 Accepted, and the shipping rate not being updated.

I was wondering what the correct way is to handle a 202 API response using this gem?

**Comment by tolgap** [comment]
Reference: https://community.shopify.com/c/Shopify-APIs-SDKs/DraftOrder-API-total-price-racing-condition-does-not-always/td-p/525634

**Comment by tanema** [comment]
👋 Hey @tolgap Thanks for opening this issue. I am sorry to not help much more but I have the same answer as the shopify community thread. You will have to fetch the draft order again after updating it. This is because we do quite a lot of background processing on the order before it is actually updated. The update should be pretty quick though.

**Comment by tolgap** [comment]
Alright, so I can always assume that reloading immediately after updating the DraftOrder will contain the latest information. Thank you 👍 .
