### ISSUE TITLE
fetch customer with orders's status "any"

### ISSUE THREAD

**Issue by illia108** [Shopify/shopify_api#762]
Is it possible to do something like this:

`ShopifyAPI::Customer.where(email: email, orders: { status: "any" })&.first`

I tried `joins` but there is no such method on ShopifyAPI::Customer
I would like to avoid making two API calls if possible.
Thanks

**Comment by paulomarg** [comment]
You can fetch all of a customer's orders in the API by calling for example:

```ruby
ShopifyAPI::Order.find(:all, :params => { :customer_id => <id>, :status => 'any' })
```

This object will include the order Customer in the response. You can find more information on that endpoint at https://shopify.dev/docs/admin-api/rest/reference/customers/customer#orders-2020-07.

However, you won't be able to search by the customer's email address, so you'll need to make two calls anyway if you don't don't have the customer's id beforehand.

Also, in the future I'd recommend you post this kind of question on the Community forums (https://community.shopify.com) where you may get faster / more complete responses. Github issues are meant to track actual bugs in the code, rather than general questions.
