### ISSUE TITLE
Support for Shortcut Methods to Minimize Network Requests 

### ISSUE THREAD

**Issue by sshaw** [Shopify/shopify_api#766]
Active Resource wants to give one the feeling of working with a Active Record model. Unfortunately  Active Record's DB connection is just a network hop away (I hope!). Usually not the case with HTTP-based APIs. 

Currently if one wants a collection's products, a product's variants, or other things, and they have the IDs of these top-level resources, they have to make an extra network call:

```rb
ShopifyAPI::Collection.find(x).products
ShopifyAPI::Product.find(x).variants
```

In addition, these requests are being rate limited, so every call counts ☎️  

Why not support calls like this: 

```rb
ShopifyAPI::Collection.products(collection_id)
ShopifyAPI::Product.variants(product_id)
```

❓ 

The foundation is there:

```rb
class Collection 
  def self.products(collection_id)
    ShopifyAPI::Product.all(
      :from => "#{ShopifyAPI::Product.prefix}collections/#{collection_id}/products.json"
    )
  end
end
```

💪

**Comment by paulomarg** [comment]
The API actually already supports that kind of request, since ActiveResource supports parameterized queries. In the example you gave, one could leverage the `collection_id` parameter from https://shopify.dev/docs/admin-api/rest/reference/products/product#index-2020-07, like so:

```ruby
ShopifyAPI::Product.find(:all, :params => { :collection_id => <id> })
```

This request would return that collection's products (including their variants!). Plus, you'd also be able to apply any other relevant filters in that same call.

While this is slightly less intuitive than your suggestion, it's a lot more flexible because it supports any number of parameters, and achieves the same end result of getting the list of products in a single request.

**Comment by sshaw** [comment]
In the collection case yes, it's similar but we just got lucky. 

In the variant case, how does one juyst select the variant ids and skus for the given product id?

Order's Risks. Given an order id, how do I get its Risks? 

Surely there are others.

**Comment by paulomarg** [comment]
I realized I pointed out the wrong docs link in my previous response, my apologies. The way ActiveResource works is that it takes the `params` argument and uses it to build the nested resource URL.

Looking at Order Risks, if we take this:

```ruby
ShopifyAPI::OrderRisk.find(:all, :params => { :order_id => 1234 })
```

And look at the URL that it actually amounts to:

```ruby
ShopifyAPI::OrderRisk.collection_path(:order_id => 1234)
# "/admin/api/2020-07/orders/1234/risks.json"
```

What we're actually hitting is the `/orders/<id>/risks` endpoint as desired. So while the shortcut methods would indeed be 'prettier', ActiveResource already supports doing what you're suggesting out of the box.

This can also be seen in the last example in the ActiveResource docs (StreetAddress), at https://api.rubyonrails.org/v3.2.6/classes/ActiveResource/Base.html#method-c-find.

I think because of this, implementing the shorthand methods as part of the API code would add a bit of unnecessary clutter to the resources, but developers can still implement these wrappers at the application level if they want to. What do you think?

**Comment by tanema** [comment]
I would also suggest, if you are looking to use your network requests in the most efficient manner then it would be best to look into crafting graphql queries instead. This is precisely the problem that graphql was created for. A REST endpoint (which activeresource is meant to adapt to) is not a query layer so we cannot possibly support all associated objects on every resource we have a REST endpoint for. GraphQL would solve this and be able to only grab the data that you specifically need along with only the fields that you need. This is especially ideal with things like orders that can get enormous.

**Comment by sshaw** [comment]
> What we're actually hitting is the /orders/<id>/risks endpoint as desired. So while the shortcut methods would indeed be 'prettier', ActiveResource already supports doing what you're suggesting out of the box.

Great thanks. The prior example wasn't 100% but I see what you mean 💪 

> I would also suggest, if you are looking to use your network requests in the most efficient manner then it would be best to look into crafting graphql queries instead. 

Heh thanks but I would classify GQL development generally as the opposite of efficient and in the case of products I'll have to add pagination to handle the variants 👎
