### ISSUE TITLE
shopify_api vs shopify_app

### ISSUE THREAD

**Issue by liondancer** [Shopify/shopify_api#792]
What I might be missing out by using the `shopify_api` library on a Rails API only site VS generating an app using `shopify_app`?

On the `shopify_app` github page I see things such as `WebhooksManager` , `ScripttagsManager` , etc. I am wondering if there is a subset of useful and critical tools I may need that does not come with `shopify_api` . Currently new and trying to learn the toolset

**Comment by paulomarg** [comment]
Hi @liondancer! `shopify_app` actually builds on top of `shopify_api`, and as you said, it adds certain functionalities to it.

The `shopify_api` gem contains all of the tools you'll need to log your app into Shopify, e.g. it gives you methods to perform the OAuth authentication, but not the actual actions to do it (which `shopify_app` provides), so it gives you more freedom to choose how to implement things.

Since the API gem provides you with the tools to log into Shopify and run queries, by itself it gives you the essentials, but you'll need to implement your app yourself. The App gem helps speed up the process and gives you those readymade functions.

Hope this helps!
