### ISSUE TITLE
How can I see "Retry-After" header value in GraphQL?

### ISSUE THREAD

**Issue by ryz310** [Shopify/shopify_api#836]
# Issue summary

The shopify admin API has rate limits: [Shopify API rate limits](https://shopify.dev/concepts/about-apis/rate-limits#graphql-admin-api-rate-limits)
I use the API via GraphQL, but unfortunately, `graphql-client` has not supported response header seeing.

See: [reponse headers are ignored\. · Issue \#160 · github/graphql\-client](https://github.com/github/graphql-client/issues/160)

How can I see `Retry-After` header value?

## Specifications

- `shopify_api` version: 9.3.0
- `graphql` version: 1.12.3
- `graphql-client` version: 0.16.0
- Shopify API version used: `2020-07`

**Comment by mllemango** [comment]
Hey @ryz310, it looks like you’re referring to the REST API’s header value there. Shopify's GraphQL API uses a different approach to rate limiting so you wouldn't need to look at response headers because the information is in the body. 
You can utilize the `extensions` part of the response to understand your throttle status. Please take a look at the [docs](https://shopify.dev/concepts/about-apis/rate-limits#graphql-admin-api-rate-limits) to understand how we calculate query costs!
```
{
  "data": {
    "shop": {
      "name": "graphql-admin"
    }
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 1,
      "actualQueryCost": 1,
      "throttleStatus": {
        "maximumAvailable": 1000,
        "currentlyAvailable": 999,
        "restoreRate": 50
      }
    }
  }
}
```

**Comment by ryz310** [comment]
Thanks @mllemango.

But I could not find the information within error response.
I'd like to see that on the error.

**Comment by thecodepixi** [comment]
Closing this because it appears to have been sufficiently answered. If needed, please open a new issue. Thanks!
