### ISSUE TITLE
Canceling order with email:false still sends cancellation email

### ISSUE THREAD

**Issue by skillmatic-co** [Shopify/shopify_api#872]
Hello, when I'm doing: 

```
shopify_order.cancel({'reason':'other','restock':true,'email':false})
```

I'm still seeing a cancellation email being sent. Am I doing this wrong?

I am seeing reason being set as other, and the items being restocked... so the only issue here is for some reason the cancellation email is still being sent when it shouldn't be.

**Comment by andyw8** [comment]
Hello @skillmatic-co, which release of the API are you using?

**Comment by skillmatic-co** [comment]
2020-04

**Comment by skillmatic-co** [comment]
@andyw8 are you saying this could be an API version issue?

**Comment by andyw8** [comment]
Hi @skillmatic-co

Thank you for reporting this problem. We are unable to investigate currently, but we will keep this issue open for other users to report if they experience the same problem, and use this information to help prioritize a fix.

You can also ask for help in the [Shopify Developer forums](https://community.shopify.com/c/shopify-apis-and-sdks/bd-p/shopify-apis-and-technology) and refer to the API Reference [Docs](https://shopify.dev/api).

**Comment by paulomarg** [comment]
Hey @skillmatic-co, I was trying to reproduce this issue, but I haven't been able to. Here's what I found using the latest versions of both `shopify_api` and `shopify_app` on a fresh app created with the CLI, using both the latest version and `2020-04`:

- During a normal request (i.e. not a webhook), I called `order.cancel` with email both as false and true. I only got the cancellation email on `true`, as expected.
- During an `orders/updated` webhook request, I got the same behaviour when cancelling an order, so emails only got sent when `email: true`.

This is what I called in my webhook (the regular request test was essentially the same):
```rb
shop.with_shopify_session do
  order = ShopifyAPI::Order.find(webhook["id"])
  order.cancel({'reason':'other','restock':true,'email':true/false})
end
```

Is there any context here I'm missing in trying to reproduce this? Are you maybe making any other changes to the order, or updating it from a different resource? Right now it doesn't look like this issue is happening on a fresh app any more.

**Comment by skillmatic-co** [comment]
@paulomarg thanks for investigating. I want to say this was related to #811, I came across both issues at the same time when I was trying to figure out why the updated email on the order was not persisting, and kept getting reverted back to the original customer's email. I'll dig more into this one specifically and report back.

**Comment by skillmatic-co** [comment]
This issue is no longer happening.
