### ISSUE TITLE
Why does `ShopifyAPI::Variant#to_hash` exclude `inventory_quantity` ?

### ISSUE THREAD

**Issue by koshigoe** [Shopify/shopify_api#930]
# Issue summary

I try to get variant's `inventory_quantity` via `ShopiryAPI::Product#to_hash`.
But `inventory_quantity` did not exist in `Hash` object.

```
> ShopifyAPI::Auth::Session.temp(shop: 'test.myshopify.com', access_token: 'token') do |session|
  variant = ShopifyAPI::Variant.create_instance(session: session, data: { inventory_item_id: 1234, inventory_quantity: 10 })
  pp variant.inventory_quantity
  pp variant.to_hash
end

10
{"inventory_item_id"=>1234}
=> {"inventory_item_id"=>1234}
```

## Expected behavior

I hope `ShopifyAPI::Variant#to_hash` include all API properties.

## Actual behavior

Some properties exclude?

## Specifications

- `shopify_api` version: 10.0.2
- Shopify API version used `2022-01`

**Comment by paulomarg** [comment]
Hey @koshigoe, thanks for reporting this! The `inventory_quantity` field can't be sent when saving, so we started filtering it out when we call `to_hash` (because that is the method we use to serialize the object for saving). In your case, we shouldn't be ignoring that field.

We'll add a parameter to `to_hash` to make that behaviour optional. That way, when you call the method you'll get all the data.
